In [2]:
import warnings
import numpy as np
import pandas as pd
import pickle
import time
import pymongo
# import matplotlib.pyplot as plt
# import plotly.graph_objs as go
# from plotly.offline import init_notebook_mode, iplot
# from sklearn.metrics import mean_squared_error
# from sklearn.model_selection import train_test_split

from keras import optimizers
from keras.utils import plot_model
from keras.models import Sequential, Model
from keras.layers.convolutional import Conv1D, MaxPooling1D
from keras.layers import Dense, LSTM, RepeatVector, TimeDistributed, Flatten
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
# %matplotlib inline
warnings.filterwarnings("ignore")

# Set seeds to make the experiment more reproducible.
# from tensorflow import set_random_seed
from numpy.random import seed
# set_random_seed(1)
seed(1)

Using TensorFlow backend.
/home/edwin/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/edwin/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/edwin/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/edwin/.local/lib/python3.7/site-packages/tensorflow/python/fra

In [138]:
training_data = pd.read_csv('./test/train.csv', parse_dates=['date'])
testing_data = pd.read_csv('./test/test.csv', parse_dates=['date'])

In [139]:
testing_data

id       date  store  item
0          0 2018-01-01      1     1
1          1 2018-01-02      1     1
2          2 2018-01-03      1     1
3          3 2018-01-04      1     1
4          4 2018-01-05      1     1
...      ...        ...    ...   ...
44995  44995 2018-03-27     10    50
44996  44996 2018-03-28     10    50
44997  44997 2018-03-29     10    50
44998  44998 2018-03-30     10    50
44999  44999 2018-03-31     10    50

[45000 rows x 4 columns]

In [140]:
print('Min date from train set: %s' % training_data['date'].min().date())
print('Max date from train set: %s' % training_data['date'].max().date())

Min date from train set: 2013-01-01
Max date from train set: 2013-06-03


In [141]:
lag_size = 1
print('Max date from train set: %s' % training_data['date'].max().date())
print('Max date from test set: %s' % testing_data['date'].max().date())
print('Forecast lag size', lag_size)

Max date from train set: 2013-06-03
Max date from test set: 2018-03-31
Forecast lag size 1


In [142]:
# daily_sales = training_data.groupby('date', as_index=False)['sales'].sum()
# store_daily_sales = training_data.groupby(['store', 'date'], as_index=False)['sales'].sum()
# item_daily_sales = training_data.groupby(['item', 'date'], as_index=False)['sales'].sum()

In [143]:
# daily_sales_sc = go.Scatter(x=daily_sales['date'], y=daily_sales['sales'])
# layout = go.Layout(title='Daily sales', xaxis=dict(title='Date'), yaxis=dict(title='Sales'))
# fig = go.Figure(data=[daily_sales_sc], layout=layout)
# iplot(fig)

In [144]:
# store_daily_sales_sc = []
# for store in store_daily_sales['store'].unique():
#     current_store_daily_sales = store_daily_sales[(store_daily_sales['store'] == store)]
#     store_daily_sales_sc.append(go.Scatter(x=current_store_daily_sales['date'], y=current_store_daily_sales['sales'], name=('Store %s' % store)))

# layout = go.Layout(title='Store daily sales', xaxis=dict(title='Date'), yaxis=dict(title='Sales'))
# fig = go.Figure(data=store_daily_sales_sc, layout=layout)
# iplot(fig)

In [145]:
# item_daily_sales_sc = []
# for item in item_daily_sales['item'].unique():
#     current_item_daily_sales = item_daily_sales[(item_daily_sales['item'] == item)]
#     item_daily_sales_sc.append(go.Scatter(x=current_item_daily_sales['date'], y=current_item_daily_sales['sales'], name=('Item %s' % item)))

# layout = go.Layout(title='Item daily sales', xaxis=dict(title='Date'), yaxis=dict(title='Sales'))
# fig = go.Figure(data=item_daily_sales_sc, layout=layout)
# iplot(fig)

In [146]:
train_gp = training_data.sort_values('date').groupby(['item', 'store', 'date'], as_index=False)
train_gp = train_gp.agg({'sales':['mean']})
train_gp.columns = ['item', 'store', 'date', 'sales']
train_gp.head()
to_return = 

SyntaxError: invalid syntax (<ipython-input-146-604ee9a554bd>, line 5)

In [147]:
def series_to_supervised(data, window=1, lag=1, dropnan=True):
    cols, names = list(), list()
    for i in range(window, 0, -1):
        cols.append(data.shift(i))
        names += [('%s(t-%d)' % (col, i)) for col in data.columns]
    cols.append(data)
    names += [('%s(t)' % (col)) for col in data.columns]
    cols.append(data.shift(-lag))
    names += [('%s(t+%d)' % (col, lag)) for col in data.columns]
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    print(agg)
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [153]:
window = 1
lag = lag_size
series = series_to_supervised(train_gp.drop('date', axis=1), window=window, lag=lag)
series

       item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
0            NaN         NaN         NaN        1         1        13   
1            1.0         1.0        13.0        1         1        11   
2            1.0         1.0        11.0        1         1        14   
3            1.0         1.0        14.0        1         1        13   
4            1.0         1.0        13.0        1         1        10   
...          ...         ...         ...      ...       ...       ...   
76503       50.0        10.0        80.0       50        10        57   
76504       50.0        10.0        57.0       50        10        70   
76505       50.0        10.0        70.0       50        10        73   
76506       50.0        10.0        73.0       50        10        82   
76507       50.0        10.0        82.0       50        10       103   

       item(t+1)  store(t+1)  sales(t+1)  
0            1.0         1.0        11.0  
1            1.0         1.0        1

item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
1            1.0         1.0        13.0        1         1        11   
2            1.0         1.0        11.0        1         1        14   
3            1.0         1.0        14.0        1         1        13   
4            1.0         1.0        13.0        1         1        10   
5            1.0         1.0        10.0        1         1        12   
...          ...         ...         ...      ...       ...       ...   
76502       50.0        10.0        49.0       50        10        80   
76503       50.0        10.0        80.0       50        10        57   
76504       50.0        10.0        57.0       50        10        70   
76505       50.0        10.0        70.0       50        10        73   
76506       50.0        10.0        73.0       50        10        82   

       item(t+1)  store(t+1)  sales(t+1)  
1            1.0         1.0        14.0  
2            1.0         1.0        13.0  
3            1.0         1.0        10.0  
4            1.0         1.0        12.0  
5            1.0         1.0        10.0  
...          ...         ...         ...  
76502       50.0        10.0        57.0  
76503       50.0        10.0        70.0  
76504       50.0        10.0        73.0  
76505       50.0        10.0        82.0  
76506       50.0        10.0       103.0  

[76506 rows x 9 columns]

In [154]:
# series.to_excel("output.xlsx") 

In [155]:
last_item = 'item(t-%d)' % window
last_store = 'store(t-%d)' % window
series = series[(series['store(t)'] == series[last_store])]
series = series[(series['item(t)'] == series[last_item])]

In [156]:
series.last

<bound method NDFrame.last of        item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
1            1.0         1.0        13.0        1         1        11   
2            1.0         1.0        11.0        1         1        14   
3            1.0         1.0        14.0        1         1        13   
4            1.0         1.0        13.0        1         1        10   
5            1.0         1.0        10.0        1         1        12   
...          ...         ...         ...      ...       ...       ...   
76502       50.0        10.0        49.0       50        10        80   
76503       50.0        10.0        80.0       50        10        57   
76504       50.0        10.0        57.0       50        10        70   
76505       50.0        10.0        70.0       50        10        73   
76506       50.0        10.0        73.0       50        10        82   

       item(t+1)  store(t+1)  sales(t+1)  
1            1.0         1.0        14.0  
2      

In [157]:
# columns_to_drop = [('%s(t+%d)' % (col, lag)) for col in ['item', 'store']]
# for i in range(window, 0, -1):
#     columns_to_drop += [('%s(t-%d)' % (col, i)) for col in ['item', 'store']]
# series.drop(columns_to_drop, axis=1, inplace=True)
# series.drop(['item(t)', 'store(t)'], axis=1, inplace=True)

In [158]:
# Label
labels_col = 'sales(t+%d)' % lag_size
labels = series[labels_col]
series_copy = series
series = series.drop(labels_col, axis=1)

X_train, X_valid, Y_train, Y_valid = train_test_split(series, labels.values, test_size=0.4, random_state=0)
print('Train set shape', X_train.shape)
print('Validation set shape', X_valid.shape)

Train set shape (45604, 8)
Validation set shape (30403, 8)


In [159]:
series_copy

item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
1            1.0         1.0        13.0        1         1        11   
2            1.0         1.0        11.0        1         1        14   
3            1.0         1.0        14.0        1         1        13   
4            1.0         1.0        13.0        1         1        10   
5            1.0         1.0        10.0        1         1        12   
...          ...         ...         ...      ...       ...       ...   
76502       50.0        10.0        49.0       50        10        80   
76503       50.0        10.0        80.0       50        10        57   
76504       50.0        10.0        57.0       50        10        70   
76505       50.0        10.0        70.0       50        10        73   
76506       50.0        10.0        73.0       50        10        82   

       item(t+1)  store(t+1)  sales(t+1)  
1            1.0         1.0        14.0  
2            1.0         1.0        13.0  
3            1.0         1.0        10.0  
4            1.0         1.0        12.0  
5            1.0         1.0        10.0  
...          ...         ...         ...  
76502       50.0        10.0        57.0  
76503       50.0        10.0        70.0  
76504       50.0        10.0        73.0  
76505       50.0        10.0        82.0  
76506       50.0        10.0       103.0  

[76007 rows x 9 columns]

In [160]:
epochs = 1
batch = 256
lr = 0.0003
adam = optimizers.Adam(lr)

In [161]:
X_train_series = X_train.values.reshape((X_train.shape[0], X_train.shape[1], 1))
X_valid_series = X_valid.values.reshape((X_valid.shape[0], X_valid.shape[1], 1))
print('Train set shape', X_train_series.shape)
print('Validation set shape', X_valid_series.shape)

Train set shape (45604, 8, 1)
Validation set shape (30403, 8, 1)


In [162]:
X_train

item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
5542         4.0         7.0         8.0        4         7        10   
13302        9.0         7.0        23.0        9         7        35   
20064       14.0         2.0        57.0       14         2        33   
5888         4.0         9.0        21.0        4         9        19   
25110       17.0         5.0        15.0       17         5        13   
...          ...         ...         ...      ...       ...       ...   
21383       14.0        10.0        50.0       14        10        71   
46193       31.0         2.0        80.0       31         2        61   
42894       29.0         1.0        32.0       29         1        52   
43854       29.0         7.0        45.0       29         7        41   
68718       45.0        10.0        60.0       45        10        40   

       item(t+1)  store(t+1)  
5542         4.0         7.0  
13302        9.0         7.0  
20064       14.0         2.0  
5888         4.0         9.0  
25110       17.0         5.0  
...          ...         ...  
21383       14.0        10.0  
46193       31.0         2.0  
42894       29.0         1.0  
43854       29.0         7.0  
68718       45.0        10.0  

[45604 rows x 8 columns]

In [163]:
Y_train

array([ 7., 44., 38., ..., 45., 45., 52.])

In [164]:
Y_valid

array([35., 14., 78., ..., 15., 19., 32.])

In [165]:
pd.DataFrame(data=Y_train)

0
0       7.0
1      44.0
2      38.0
3      26.0
4      16.0
...     ...
45599  55.0
45600  61.0
45601  45.0
45602  45.0
45603  52.0

[45604 rows x 1 columns]

In [166]:
pd.DataFrame(data=Y_valid)

0
0      35.0
1      14.0
2      78.0
3      43.0
4      24.0
...     ...
30398  68.0
30399  66.0
30400  15.0
30401  19.0
30402  32.0

[30403 rows x 1 columns]

In [167]:
model_cnn = Sequential()
model_cnn.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(X_train_series.shape[1], X_train_series.shape[2])))
model_cnn.add(MaxPooling1D(pool_size=2))
model_cnn.add(Flatten())
model_cnn.add(Dense(50, activation='relu'))
model_cnn.add(Dense(1))
model_cnn.compile(loss='mse', optimizer=adam)
model_cnn.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_2 (Conv1D)            (None, 7, 64)             192       
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, 3, 64)             0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 192)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 50)                9650      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 51        
Total params: 9,893
Trainable params: 9,893
Non-trainable params: 0
_________________________________________________________________


In [168]:
cnn_history = model_cnn.fit(X_train_series, Y_train, validation_data=(X_valid_series, Y_valid), epochs=epochs, verbose=2)

Train on 45604 samples, validate on 30403 samples
Epoch 1/1
 - 3s - loss: 133.4308 - val_loss: 118.6695


In [169]:
# cnn_train_pred = model_cnn.predict(X_train_series)
cnn_valid_pred = model_cnn.predict(X_valid_series)
# print('Train rmse:', np.sqrt(mean_squared_error(Y_train, cnn_train_pred)))
# print('Validation rmse:', np.sqrt(mean_squared_error(Y_valid, cnn_valid_pred)))
X_valid

item(t-1)  store(t-1)  sales(t-1)  item(t)  store(t)  sales(t)  \
41958       28.0         5.0        29.0       28         5        25   
50839       34.0         3.0        12.0       34         3        19   
38253       25.0        10.0        67.0       25        10        79   
68930       46.0         1.0        23.0       46         1        26   
31680       21.0         8.0        21.0       21         8        30   
...          ...         ...         ...      ...       ...       ...   
56814       38.0         2.0        64.0       38         2        63   
15525       11.0         2.0        61.0       11         2        44   
7533         5.0        10.0        12.0        5        10        10   
20879       14.0         7.0        27.0       14         7        30   
54197       36.0         5.0        35.0       36         5        20   

       item(t+1)  store(t+1)  
41958       28.0         5.0  
50839       34.0         3.0  
38253       25.0        10.0  
68930       46.0         1.0  
31680       21.0         8.0  
...          ...         ...  
56814       38.0         2.0  
15525       11.0         2.0  
7533         5.0        10.0  
20879       14.0         7.0  
54197       36.0         5.0  

[30403 rows x 8 columns]

In [170]:
cnn_valid_pred

array([[26.44479 ],
       [15.017297],
       [70.76746 ],
       ...,
       [11.091042],
       [28.504766],
       [26.662725]], dtype=float32)

In [171]:
cnn_train_pred = model_cnn.predict(X_train_series)
cnn_valid_pred = model_cnn.predict(X_valid_series)
print('Train rmse:', np.sqrt(mean_squared_error(Y_train, cnn_train_pred)))
print('Validation rmse:', np.sqrt(mean_squared_error(Y_valid, cnn_valid_pred)))

Train rmse: 10.804962134018941
Validation rmse: 10.893553071381502


In [172]:
cnn_train_pred = model_cnn.predict(X_train_series)
cnn_valid_pred = model_cnn.predict(X_valid_series)
print('Train rmse:', np.sqrt(mean_squared_error(Y_train, cnn_train_pred)))
print('Validation rmse:', np.sqrt(mean_squared_error(Y_valid, cnn_valid_pred)))

Train rmse: 10.804962134018941
Validation rmse: 10.893553071381502


In [173]:
Y_train

array([ 7., 44., 38., ..., 45., 45., 52.])

In [174]:
cnn_train_pred

array([[ 9.402388],
       [29.246765],
       [40.400177],
       ...,
       [41.854942],
       [41.60445 ],
       [47.43506 ]], dtype=float32)

In [175]:
X_valid_series

array([[[28.],
        [ 5.],
        [29.],
        ...,
        [25.],
        [28.],
        [ 5.]],

       [[34.],
        [ 3.],
        [12.],
        ...,
        [19.],
        [34.],
        [ 3.]],

       [[25.],
        [10.],
        [67.],
        ...,
        [79.],
        [25.],
        [10.]],

       ...,

       [[ 5.],
        [10.],
        [12.],
        ...,
        [10.],
        [ 5.],
        [10.]],

       [[14.],
        [ 7.],
        [27.],
        ...,
        [30.],
        [14.],
        [ 7.]],

       [[36.],
        [ 5.],
        [35.],
        ...,
        [20.],
        [36.],
        [ 5.]]])

In [30]:
def save_model_to_db2(model, client, db, dbconnection, model_name):
    pickled_model = pickle.dumps(model)
    myclient = pymongo.MongoClient(client)
    mydb = myclient[db]
    mycon = mydb[dbconnection]
    info = mycon.insert_one({model_name: pickled_model, 'name': model_name, 'created_time':time.time()})

In [31]:
def save_model_to_db(model, model_type, user):
    client ='mongodb://root:root123@ds353378.mlab.com:53378/cross-entropy?authSource=cross-entropy&retryWrites=false'
    db = 'cross-entropy'
    dbconnection = 'predictive_models' 
    pickled_model = pickle.dumps(model)
    myclient = pymongo.MongoClient(client)
    mydb = myclient[db]
    mycon = mydb[dbconnection]
    info = mycon.insert_one({ 'model': pickled_model, 'type': model_type, 'created_time': time.time(), 'user': user })

In [32]:
save_model_to_db(model = model_cnn, model_type = 'Prediccion de inventario', user='escruz')

In [33]:
def load_saved_model_from_db(model_type, user):
    client ='mongodb://root:root123@ds353378.mlab.com:53378/cross-entropy?authSource=cross-entropy&retryWrites=false'
    db = 'cross-entropy'
    dbconnection = 'predictive_models' 
    json_data = {}
    myclient = pymongo.MongoClient(client)
    mydb = myclient[db]
    mycon = mydb[dbconnection]
    data = mycon.find({'type': model_type, 'user': user })
    
    for i in data:
        json_data = i
    pickled_model = json_data['model']
    return pickle.loads(pickled_model)

In [34]:
loaded_model  = load_saved_model_from_db(model_type='cnn', user='escruz')

KeyError: 'model'

In [ ]:
def load_saved_model_from_db2(model_name, client, db, dbconnection):
    json_data = {}
    myclient = pymongo.MongoClient(client)
    mydb = myclient[db]
    mycon = mydb[dbconnection]
    data = mycon.find({'name': model_name})
    
    for i in data:
        json_data = i
    pickled_model = json_data[model_name]
    return pickle.loads(pickled_model)

In [ ]:
loaded_model  = load_saved_model_from_db2(client ='mongodb://root:root123@ds353378.mlab.com:53378/cross-entropy?authSource=cross-entropy&retryWrites=false', 
                           db = 'cross-entropy', 
                           dbconnection = 'predictive_models', model_name = 'cnn')

In [35]:
cnn_train_pred = model_cnn.predict(X_train_series)
cnn_valid_pred = model_cnn.predict(X_valid_series)
cnn2_train_pred = loaded_model.predict(X_train_series)
cnn2_valid_pred = loaded_model.predict(X_valid_series)
print('Train rmse:', np.sqrt(mean_squared_error(Y_train, cnn_train_pred)))
print('Validation rmse:', np.sqrt(mean_squared_error(Y_valid, cnn_valid_pred)))
print('Train rmse2:', np.sqrt(mean_squared_error(Y_train, cnn2_train_pred)))
print('Validation rmse2:', np.sqrt(mean_squared_error(Y_valid, cnn2_valid_pred)))


NameError: name 'loaded_model' is not defined

In [ ]:
def series_to_supervised(data, window=1, lag=1, dropnan=True):
    cols, names = list(), list()
    for i in range(window, 0, -1):
        cols.append(data.shift(i))
        names += [('%s(t-%d)' % (col, i)) for col in data.columns]
    cols.append(data)
    names += [('%s(t)' % (col)) for col in data.columns]
    cols.append(data.shift(-lag))
    names += [('%s(t+%d)' % (col, lag)) for col in data.columns]
    agg = pd.concat(cols, axis=1)
    agg.columns = names
    if dropnan:
        agg.dropna(inplace=True)
    return agg

In [ ]:
months = 1
lag_size = months * 30
training_data['date'] = pd.to_datetime(training_data['date'])
train_gp = training_data.sort_values('date').groupby(
    ['item', 'store', 'date'], as_index=False)
train_gp = train_gp.agg({'sales': ['mean']})
train_gp.columns = ['item', 'store', 'date', 'sales']
window = 120     
lag = lag_size
series = series_to_supervised(train_gp.drop(
    'date', axis=1), window=window, lag=lag)
last_item = 'item(t-%d)' % window
last_store = 'store(t-%d)' % window
series = series[(series['store(t)'] == series[last_store])]
series = series[(series['item(t)'] == series[last_item])]
columns_to_drop = [('%s(t+%d)' % (col, lag)) for col in ['item', 'store']]
for i in range(window, 0, -1):
    columns_to_drop += [('%s(t-%d)' % (col, i))
                        for col in ['item', 'store']]
series.drop(columns_to_drop, axis=1, inplace=True)
series.drop(['item(t)', 'store(t)'], axis=1, inplace=True)
labels_col = 'sales(t+%d)' % lag_size
labels = series[labels_col]
series = series.drop(labels_col, axis=1)

X_train, X_valid, Y_train, Y_valid = train_test_split(
    series, labels.values, test_size=0.4, random_state=0)
X_train_series = X_train.values.reshape(
    (X_train.shape[0], X_train.shape[1], 1))
X_valid_series = X_valid.values.reshape(
    (X_valid.shape[0], X_valid.shape[1], 1))
trained_data = {'data':{'X_train_series': X_train_series, 'Y_train': Y_train, 'X_valid_series': X_valid_series, 'Y_valid': Y_valid}}

In [36]:
def train_model(X_train_series, X_valid_series, Y_train, Y_valid):
    epochs = 40
    lr = 0.0003
    adam = optimizers.Adam(lr)
    model_cnn = Sequential()
    model_cnn.add(Conv1D(filters=64, kernel_size=2, activation='relu', input_shape=(
        X_train_series.shape[1], X_train_series.shape[2])))
    model_cnn.add(MaxPooling1D(pool_size=2))
    model_cnn.add(Flatten())
    model_cnn.add(Dense(50, activation='relu'))
    model_cnn.add(Dense(1))
    model_cnn.compile(loss='mse', optimizer=adam)
    model_cnn.summary()

    cnn_history = model_cnn.fit(X_train_series, Y_train, validation_data=(
        X_valid_series, Y_valid), epochs=epochs, verbose=2)

In [37]:
t = pd.io.json.json_normalize(trained_data['data'])

NameError: name 'trained_data' is not defined

In [38]:
df = t.iloc[0]

NameError: name 't' is not defined

In [39]:
train_model(df['X_train_series'], df['X_valid_series'], df['Y_train'], df['Y_valid'])

NameError: name 'df' is not defined

In [40]:
cnn_history

In [41]:
cnn_train_pred = model_cnn.predict(X_train_series)
cnn_valid_pred = model_cnn.predict(X_valid_series)

In [42]:
series

sales(t-10)  sales(t-9)  sales(t-8)  sales(t-7)  sales(t-6)  \
10            13.0        11.0        14.0        13.0        10.0   
11            11.0        14.0        13.0        10.0        12.0   
12            14.0        13.0        10.0        12.0        10.0   
13            13.0        10.0        12.0        10.0         9.0   
14            10.0        12.0        10.0         9.0        12.0   
...            ...         ...         ...         ...         ...   
74741         20.0        31.0        25.0        18.0        24.0   
74742         31.0        25.0        18.0        24.0        21.0   
74743         25.0        18.0        24.0        21.0        19.0   
74744         18.0        24.0        21.0        19.0        27.0   
74745         24.0        21.0        19.0        27.0        27.0   

       sales(t-5)  sales(t-4)  sales(t-3)  sales(t-2)  sales(t-1)  sales(t)  
10           12.0        10.0         9.0        12.0         9.0         9  
11           10.0         9.0        12.0         9.0         9.0         7  
12            9.0        12.0         9.0         9.0         7.0        10  
13           12.0         9.0         9.0         7.0        10.0        12  
14            9.0         9.0         7.0        10.0        12.0         5  
...           ...         ...         ...         ...         ...       ...  
74741        21.0        19.0        27.0        27.0        28.0        18  
74742        19.0        27.0        27.0        28.0        18.0        28  
74743        27.0        27.0        28.0        18.0        28.0        21  
74744        27.0        28.0        18.0        28.0        21.0        33  
74745        28.0        18.0        28.0        21.0        33.0        29  

[69856 rows x 11 columns]